version: '3.4'

services:
  rabbitmq:
    image: rabbitmq:3.9.21-management
    container_name: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
      - 15692:15692
    environment:
      - RABBITMQ_DEFAULT_USER=chat
      - RABBITMQ_DEFAULT_PASS=chat